package relampagorojo93.MMOHorses.Modules.EntityPckg.Interfaces.Objects.NBT.Enums;

public enum DamageSource {
	INFIRE, LIGHTNINGBOLT, ONFIRE, LAVAL, HOTFLOOR, INWALL, CRAMMING, DROWN, STARVE, CACTUS, FALL, FLYINTOWALL,
	OUTOFWORLD, GENERIC, MAGIC, WITHER, ANVIL, FALLINGBLOCK, DRAGONBREATH, DRYOUT, SWEETBERRYBUSH, STING, MOB, PLAYER,
	ARROW, TRIDEN, FIREWORKS, WITHERSKULL, THROWN, INDIRECTMAGIC, THORNS, EXPLOSION_PLAYER;
}
